とりあえずHTMLを書きました
watanabeminami/training.frontend pull request #10
Opened 2017-04-24 10:03 UTC by watanabeminami

##　変更点

- class名の変更
- ulの使用
- submitボタンの変更
- footerの変更

2017-04-25 02:01 UTC, motoki-oomura requested changes
めっちゃいいですね！
１ヶ月目とは思えないようなHTMLの書き方担ってきました！

まだまだ、改善するところはありそうですが、それはプロでも頭を悩ますぐらいのところが多々あったりする（ここにクラスをつけるべきなのか、シングルクラスにするのか、マルチクラスにするのか等）ので、焦る必要はないです！

とりあえず、僕がコメントしたところはもう一度考えてみてください！

2017-04-25 02:01 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +    <p>Check out some of my works.</p>
上のpタグと下のpタグは見た目が違うと思いますが、classをつけずにどうやってスタイリングしますか？

2017-04-25 02:01 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +    <ul class= "buttons">
class名は最低２語つけましょう 「xxxx-xxxxx」みたいな。
そのときに「何の-何」みたいな感じでつけるといいです。
site-headerであれば　site(webサイト)のheader みたいな感じです。

2017-04-25 02:01 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +      <li><a class="button" href="#send-message">SEND MESSAGE</a></li>
これらのボタンですが、色が違う指定はどうやって表現しますか？
この場合はマルチクラスの考え方を用いてください。

2017-04-25 02:01 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +        <h2 class="section-titles about-title" id="learn-more">ABOUT ME</h2>
titles　とタイトルが謎に複数形になってます。

2017-04-25 02:01 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +      <header class="section-header works-header">
ヘッダーに対して共通クラス、ユニーククラスを２つつける（マルチクラス）を用いる理由は何ですか？

2017-04-25 02:01 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +            <img src="images/image1.jpg" alt="夜空と木の写真" class= "works-contents-images works-contents-image1">
imgにクラスをつける理由は何ですか？

2017-04-25 02:01 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +              <button type="button" name="button">READ MORE</button>
ここのbuttonタグは ヘッダーと同じように、違うタグを使ったらどうですか？
このボタンはどちらかというとリンクの意味を持っている気がします。

2017-04-25 03:17 UTC, watanabeminami commented on HTML.CSS/02.Advanced/index.HTML
> +    <p>Check out some of my works.</p>
たしかに…。
h1はページに一つしかないということでしたので、h1+p というセレクタにして、
h1の後のpにだけ異なるデザインをする　とかでしょうか？

2017-04-25 03:21 UTC, watanabeminami commented on HTML.CSS/02.Advanced/index.HTML
> +      <header class="section-header works-header">
すみません。とりあえずでつけていました。_

2017-04-25 03:21 UTC, watanabeminami commented on HTML.CSS/02.Advanced/index.HTML
> +        <h2 class="section-titles about-title" id="learn-more">ABOUT ME</h2>
直しました。

2017-04-25 03:21 UTC, watanabeminami commented on HTML.CSS/02.Advanced/index.HTML
> +      <li><a class="button" href="#send-message">SEND MESSAGE</a></li>
eader-button header-button-1 のように二つ名前をつけました

2017-04-25 03:21 UTC, watanabeminami commented on HTML.CSS/02.Advanced/index.HTML
> +    <ul class= "buttons">
buttonのところでしょうか？　クラス名変更いたしました。

2017-04-25 03:22 UTC, watanabeminami commented on HTML.CSS/02.Advanced/index.HTML
> +            <img src="images/image1.jpg" alt="夜空と木の写真" class= "works-contents-images works-contents-image1">
後で何かいじる時があるのかと、とりあえずでつけていました。

2017-04-25 03:24 UTC, watanabeminami commented on HTML.CSS/02.Advanced/index.HTML
> +              <button type="button" name="button">READ MORE</button>
もともとサンプルオリジナルのHTMLはaタグだったのですが、ボタンでいいんじゃないかと思い
変えてしまいました。直します

2017-04-25 06:09 UTC, motoki-oomura reviewed
コメントしましたー！

2017-04-25 06:09 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +    <p>Check out some of my works.</p>
`h1 + p` でもよかったりしますが、僕の場合は面倒なので class をつけちゃいます！

2017-04-25 06:09 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +    <ul class= "buttons">
ulのところは変わってないですよー。

ちなみにheader-button　という名前にするとheader以外のところで使えなくなるので、
もっとグローバルに使える名前にしたほうがいいですね！

2017-04-25 10:11 UTC, watanabeminami commented
wip workをいじり中です、

2017-04-27 11:28 UTC, watanabeminami commented
worksを引き続きいじっています。
afterのバックグラウンドに画像をいれているはずなのですが、スクロールと共に
画像が動いてしまう状態が直せずにいます。
ここらへんの構造を把握して、どうゆうことになっているのか整理してい行こうとおもいます。

2017-05-02 06:59 UTC, watanabeminami commented
大まかな部分は治ったと思います。

2017-05-02 08:12 UTC, watanabeminami commented
スマホ画面でのボタンずれの修正
画面幅のずれの修正
hover時のカーソルのアイコンの修正
をいたしました。

2017-05-02 10:02 UTC, watanabeminami commented
windows だとスクロールバーがでてしまい、それを消そうと奮闘していましたが、高橋さんからそれはそうゆうものだと聞きました、なのでマージさせていただきます。

2017-05-08 06:38 UTC, motoki-oomura approved these changes
okですが、微々たるところコメントしました！

2017-05-08 06:38 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.css
> +html{
- セレクタとセレクタの間に改行を入れてください
- セレクタとブラケット `{ ` の間にスペースを入れてください。

```
padding: 0;
margin: 0;
}
         <= ここの部分
html {
```

2017-05-08 06:38 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.css
> +.site-main{}
空のセレクタは消しましょう！

2017-05-08 06:38 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.css
> +  position:relative;
プロパティと値の間にはスペースを入れましょう！
```
position: relative;
```

2017-05-08 06:38 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.css
> +.about-main>p{
スペースいれよう！
```
.about > p {
```

2017-05-08 06:38 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.css
> +.skills-main,{
ここらへんからインデントがおかしくなってる？

2017-05-08 06:39 UTC, motokioomura commented on HTML.CSS/02.Advanced/index.HTML
> +          <li class= "li-works-contents li-works-contents4">
class= と "li-... の間に謎のスペースが！
他にもあるよ！

2017-05-08 06:39 UTC, watanabeminami commented on HTML.CSS/02.Advanced/index.HTML
> +          <li class= "li-works-contents li-works-contents4">
ありがとうございます！！！　直して行きます！

2017-05-08 07:21 UTC, merged